package mocks

import mock "github.com/stretchr/testify/mock"
import storage "github.com/gabesullice/phargo/storage"

// Condition is an autogenerated mock type for the Condition type
type Condition struct {
	mock.Mock
}

// Assertion provides a mock function with given fields:
func (_m *Condition) Assertion() storage.Assertion {
	ret := _m.Called()

	var r0 storage.Assertion
	if rf, ok := ret.Get(0).(func() storage.Assertion); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(storage.Assertion)
	}

	return r0
}

// Conditions provides a mock function with given fields:
func (_m *Condition) Conditions() []storage.Condition {
	ret := _m.Called()

	var r0 []storage.Condition
	if rf, ok := ret.Get(0).(func() []storage.Condition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Condition)
		}
	}

	return r0
}

// Conjunction provides a mock function with given fields:
func (_m *Condition) Conjunction() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsGroup provides a mock function with given fields:
func (_m *Condition) IsGroup() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

var _ storage.Condition = (*Condition)(nil)
