package mocks

import mock "github.com/stretchr/testify/mock"
import storage "github.com/gabesullice/phargo/storage"

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: q
func (_m *Executor) Execute(q storage.Query) (storage.Fetcher, error) {
	ret := _m.Called(q)

	var r0 storage.Fetcher
	if rf, ok := ret.Get(0).(func(storage.Query) storage.Fetcher); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.Fetcher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(storage.Query) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ storage.Executor = (*Executor)(nil)
