package mocks

import mock "github.com/stretchr/testify/mock"
import storage "github.com/gabesullice/phargo/storage"

// Preparer is an autogenerated mock type for the Preparer type
type Preparer struct {
	mock.Mock
}

// Prepare provides a mock function with given fields: q
func (_m *Preparer) Prepare(q storage.Query) (storage.Runner, error) {
	ret := _m.Called(q)

	var r0 storage.Runner
	if rf, ok := ret.Get(0).(func(storage.Query) storage.Runner); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.Runner)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(storage.Query) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ storage.Preparer = (*Preparer)(nil)
